[env:GP_base]
extends = esp32_base
board = dpu_esp32
board_level = extra

build_flags =
  ${esp32_base.build_flags}
  -D PRIVATE_HW
  -I variants/esp32/diy/GP_base
  -D OLED_UA
  -D GUI_UA
  
board_build.arduino.memory_type = qio_qspi
board_build.partitions = large_spiffs_no_ota_8MB.csv
board_build.psram_type = qio

lib_deps =
  ${esp32_base.lib_deps}
  bblanchon/ArduinoJson@^7.4.3