[env:GP_base2]
extends = esp32_base
board = dpu_esp32
board_level = extra

build_flags =
  ${esp32_base.build_flags}
  -D PRIVATE_HW
  -I variants/esp32/diy/GP_base2

board_build.arduino.memory_type = qio_qspi
board_build.partitions = large_spiffs_no_ota_8MB.csv
board_build.psram_type = qio